services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: spin_playlist
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/spin_playlist
      SECRET_KEY: your-secret-key-change-in-production
      YOUTUBE_API_KEY: ${YOUTUBE_API_KEY:-}
    depends_on:
      - db
    volumes:
      - ./backend:/app/backend

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3001:3000"
    volumes:
      - ./src:/app/src
      - ./public:/app/public
    environment:
      - REACT_APP_API_URL=http://localhost:8000

volumes:
  postgres_data:
